# mkdocs.yml
# Configuration file for MkDocs (Automated project documentation generator)

site_name: Civic Paperkit
site_url: https://civic-interconnect.github.io/civic-paperkit/
repo_url: https://github.com/civic-interconnect/civic-paperkit
site_description: Toolkit for managing research paper assets and bibliographies.
site_author: Civic Interconnect
docs_dir: docs
site_dir: site
copyright: Copyright &copy; 2025 Civic Interconnect
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/civic-interconnect

theme:
  name: material
  features:
    - navigation.expand
    - navigation.sections # Group navigation items
    - navigation.top # Back-to-top button
    - search.suggest # Search suggestions as you type
    - search.highlight # Highlight search terms
    - content.code.copy # Copy button on code blocks
    - toc.follow # Highlight current section in TOC

  palette:
    - scheme: default # Light/dark mode toggle
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - mike:
      version_selector: true
      css_dir: css
      javascript_dir: js
      canonical_version: latest
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            show_source: true
            show_root_heading: true # Include module names
            show_root_toc_entry: true # Include module in TOC
            docstring_style: numpy # Professional docstring format
            show_signature_annotations: true
            separate_signature: true # Makes function signatures easier to read

markdown_extensions:
  - admonition # Note/Warning/Tip boxes
  - codehilite # Syntax highlighting
  - tables # Markdown tables
  - toc:
      permalink: true # Clickable headers
      toc_depth: 3
  - pymdownx.superfences # Code blocks with syntax highlighting
  - pymdownx.details # Collapsible sections
  - pymdownx.inlinehilite  # Inline code highlighting
  - pymdownx.snippets  # Include external files
  - pymdownx.tabbed  # Tabbed content

nav:
  - Home: index.md
  - API Reference: api.md
